"""Shared test fixtures.

The golden policy is generated rather than committed as a binary blob, so the
test suite works from a fresh clone and the PDF can never drift from the label
file that describes it - both come from the same generator script.
"""

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
GOLDEN_DIR = REPO_ROOT / "evals" / "golden"
GOLDEN_PDF = GOLDEN_DIR / "synthetic-health-policy.pdf"
HOSTILE_PDF = GOLDEN_DIR / "synthetic-hostile-policy.pdf"
GOLDEN_LABELS = GOLDEN_DIR / "synthetic-health-policy.labels.json"
BUILDER = GOLDEN_DIR / "build_synthetic_policy.py"


@pytest.fixture(scope="session")
def golden_pdf() -> Path:
    if not GOLDEN_PDF.exists():
        subprocess.run([sys.executable, str(BUILDER)], check=True, cwd=REPO_ROOT)
    return GOLDEN_PDF


@pytest.fixture(scope="session")
def golden_labels(golden_pdf: Path) -> list[dict]:
    return json.loads(GOLDEN_LABELS.read_text(encoding="utf-8"))["clauses"]


@pytest.fixture(scope="session")
def hostile_pdf() -> Path:
    """The same policy typeset with one uniform font and no bold.

    Exists to stop the segmenter's tests being circular. The styled golden PDF
    is generated by this repo and the size thresholds were tuned against it, so
    passing on it alone proves very little. This variant removes every styling
    signal, leaving only clause numbering and ALL-CAPS section names - the
    situation many real machine-generated policy PDFs present.
    """
    if not HOSTILE_PDF.exists():
        subprocess.run([sys.executable, str(BUILDER)], check=True, cwd=REPO_ROOT)
    return HOSTILE_PDF
